/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Base_Plate.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/robot_grippter/Base_Plate.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Solid1.geometry} material={materials.ChromePolishedBlack} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/robot_grippter/Base_Plate.glb')
