/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 BASE.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BASE(props) {
  const { nodes, materials } = useGLTF('/models/suspension/BASE.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.1}>
        <mesh geometry={nodes.Solid1_1.geometry} material={materials.AnodizedBlack} />
        <mesh geometry={nodes.Solid1_2.geometry} material={materials.ChromePolished} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/suspension/BASE.glb')
